version: '3.5'

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    container_name: zabbix-server
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - zbx-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    container_name: zabbix-web
    ports:
      - "8080:8080"
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - zabbix-server
    networks:
      - zbx-net

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-latest
    container_name: zabbix-agent
    ports:
      - "10060:10050"
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVERACTIVE: zabbix-server
      ZBX_HOSTNAME: "zabbix-docker-agent"
    networks:
      - zbx-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zbx-net

volumes:
  pgdata:

networks:
  zbx-net:
    driver: bridge
